version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

  php:
    image: php:8.1-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4500:4500"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php

